# Generated by Django 2.0.6 on 2018-06-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('produto', models.CharField(max_length=200, verbose_name='Descricao do Produto')),
                ('quantidade', models.IntegerField(verbose_name='Qunatidade de Produto')),
                ('preco_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do Produto')),
            ],
        ),
    ]
